### ISSUE TITLE
Рыцарь.py

### ISSUE THREAD

**Issue by KotikeD0staff** [Morph-life/Python#1]
The game is not finished and last function  doesn't work. 
Fix to...
The 2nd of July
-label:bug

**Comment by KotikeD0staff** [comment]
#bug

**Comment by KotikeD0staff** [comment]
Oh, admin... Can you fix it, please?

**Comment by KotikeD** [comment]
Okay, we know that. The project (game) doesn't finished yet. When we finished something we always notice people. The best programmers working on it now. #End

If you are not satisfied with our answer, you can write about it to us by email. Please do not reopen the issue! Thank you, goodbye!
